sm8550-common: Fix the paths
FATAL EXCEPTION: main
Process: org.lineageos.settings, PID: 12548
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.lineageos.settings/org.lineageos.settings.zram.ZramActivity}: android.view.InflateException: Binary XML file line #23: Error inflating class (not found)com.xiaomi.settings.CustomSeekBarPreference
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4206)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4393)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:222)
 at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
 at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2773)
 at android.os.Handler.dispatchMessage(Handler.java:109)
 at android.os.Looper.loopOnce(Looper.java:232)
 at android.os.Looper.loop(Looper.java:317)
 at android.app.ActivityThread.main(ActivityThread.java:8935)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class (not found)com.xiaomi.settings.CustomSeekBarPreference
 at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:291)
 at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:349)
 at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:351)
 at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:161)
 at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:112)
 at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:215)
 at androidx.preference.PreferenceFragment.setPreferencesFromResource(PreferenceFragment.java:407)
 at org.lineageos.settings.zram.ZramSettingsFragment.onCreatePreferences(ZramSettingsFragment.java:42)
 at androidx.preference.PreferenceFragment.onCreate(PreferenceFragment.java:168)
 at android.app.Fragment.performCreate(Fragment.java:2491)
 at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
 at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
 at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
 at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
 at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
 at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
 at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
 at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:185)
 at android.app.Activity.performCreate(Activity.java:9088)
 at android.app.Activity.performCreate(Activity.java:9057)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1535)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4188)
 ... 13 more
Caused by: java.lang.ClassNotFoundException: com.xiaomi.settings.CustomSeekBarPreference
 at java.lang.Class.classForName(Native Method)
 at java.lang.Class.forName(Class.java:607)
 at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:218)
 at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:281)
 ... 34 more
Caused by: java.lang.ClassNotFoundException: com.xiaomi.settings.CustomSeekBarPreference
 ... 38 more